import type { Metadata } from "next";
import {NuqsAdapter} from "nuqs/adapters/next/app"
import "./globals.css";
import HeaderHome from "@/app/components/HeaderHome/HeaderHome"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
     
    >
      <body className="min-h-full flex flex-col">
        <HeaderHome />
        <NuqsAdapter>
          {children}
        </NuqsAdapter>
        </body>
    </html>
  );
}
